/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerReviewsRouteImport } from './routes/seller.reviews'
import { Route as SellerReportsRouteImport } from './routes/seller.reports'
import { Route as SellerPromotionsRouteImport } from './routes/seller.promotions'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerFinanceRouteImport } from './routes/seller.finance'
import { Route as SellerCustomersRouteImport } from './routes/seller.customers'
import { Route as SellerCouponsRouteImport } from './routes/seller.coupons'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReportsRoute = SellerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPromotionsRoute = SellerPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerFinanceRoute = SellerFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCustomersRoute = SellerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCouponsRoute = SellerCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => SellerRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reports': typeof SellerReportsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reports': typeof SellerReportsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reports': typeof SellerReportsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/messages'
    | '/seller'
    | '/admin/finance'
    | '/category/$slug'
    | '/product/$id'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/finance'
    | '/seller/orders'
    | '/seller/promotions'
    | '/seller/reports'
    | '/seller/reviews'
    | '/seller/settings'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/messages'
    | '/seller'
    | '/admin/finance'
    | '/category/$slug'
    | '/product/$id'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/finance'
    | '/seller/orders'
    | '/seller/promotions'
    | '/seller/reports'
    | '/seller/reviews'
    | '/seller/settings'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/messages'
    | '/seller'
    | '/admin/finance'
    | '/category/$slug'
    | '/product/$id'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/finance'
    | '/seller/orders'
    | '/seller/promotions'
    | '/seller/reports'
    | '/seller/reviews'
    | '/seller/settings'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  MessagesRoute: typeof MessagesRoute
  SellerRoute: typeof SellerRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reports': {
      id: '/seller/reports'
      path: '/reports'
      fullPath: '/seller/reports'
      preLoaderRoute: typeof SellerReportsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/promotions': {
      id: '/seller/promotions'
      path: '/promotions'
      fullPath: '/seller/promotions'
      preLoaderRoute: typeof SellerPromotionsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/finance': {
      id: '/seller/finance'
      path: '/finance'
      fullPath: '/seller/finance'
      preLoaderRoute: typeof SellerFinanceRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/customers': {
      id: '/seller/customers'
      path: '/customers'
      fullPath: '/seller/customers'
      preLoaderRoute: typeof SellerCustomersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/coupons': {
      id: '/seller/coupons'
      path: '/coupons'
      fullPath: '/seller/coupons'
      preLoaderRoute: typeof SellerCouponsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFinanceRoute: typeof AdminFinanceRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinanceRoute: AdminFinanceRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerCouponsRoute: typeof SellerCouponsRoute
  SellerCustomersRoute: typeof SellerCustomersRoute
  SellerFinanceRoute: typeof SellerFinanceRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPromotionsRoute: typeof SellerPromotionsRoute
  SellerReportsRoute: typeof SellerReportsRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerCouponsRoute: SellerCouponsRoute,
  SellerCustomersRoute: SellerCustomersRoute,
  SellerFinanceRoute: SellerFinanceRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPromotionsRoute: SellerPromotionsRoute,
  SellerReportsRoute: SellerReportsRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  MessagesRoute: MessagesRoute,
  SellerRoute: SellerRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
