/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SellerSubscriptionRouteImport } from './routes/seller.subscription'
import { Route as SellerStockRouteImport } from './routes/seller.stock'
import { Route as SellerShippingRouteImport } from './routes/seller.shipping'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerReviewsRouteImport } from './routes/seller.reviews'
import { Route as SellerReportsRouteImport } from './routes/seller.reports'
import { Route as SellerPromotionsRouteImport } from './routes/seller.promotions'
import { Route as SellerProfileRouteImport } from './routes/seller.profile'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerHelpRouteImport } from './routes/seller.help'
import { Route as SellerFinanceRouteImport } from './routes/seller.finance'
import { Route as SellerCustomersRouteImport } from './routes/seller.customers'
import { Route as SellerCouponsRouteImport } from './routes/seller.coupons'
import { Route as SellerAdsRouteImport } from './routes/seller.ads'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrderSuccessRouteImport } from './routes/order.success'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCarouselRouteImport } from './routes/admin.carousel'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicMelhorEnvioWebhookRouteImport } from './routes/api/public/melhor-envio/webhook'
import { Route as ApiPublicMelhorEnvioOauthCallbackRouteImport } from './routes/api/public/melhor-envio/oauth-callback'
import { Route as ApiPublicHooksAdSchedulerRouteImport } from './routes/api/public/hooks/ad-scheduler'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SellerSubscriptionRoute = SellerSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SellerRoute,
} as any)
const SellerStockRoute = SellerStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => SellerRoute,
} as any)
const SellerShippingRoute = SellerShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReportsRoute = SellerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPromotionsRoute = SellerPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProfileRoute = SellerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerHelpRoute = SellerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => SellerRoute,
} as any)
const SellerFinanceRoute = SellerFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCustomersRoute = SellerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCouponsRoute = SellerCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAdsRoute = SellerAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => SellerRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order/success',
  path: '/order/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarouselRoute = AdminCarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMelhorEnvioWebhookRoute =
  ApiPublicMelhorEnvioWebhookRouteImport.update({
    id: '/api/public/melhor-envio/webhook',
    path: '/api/public/melhor-envio/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMelhorEnvioOauthCallbackRoute =
  ApiPublicMelhorEnvioOauthCallbackRouteImport.update({
    id: '/api/public/melhor-envio/oauth-callback',
    path: '/api/public/melhor-envio/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAdSchedulerRoute =
  ApiPublicHooksAdSchedulerRouteImport.update({
    id: '/api/public/hooks/ad-scheduler',
    path: '/api/public/hooks/ad-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order/success': typeof OrderSuccessRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/ads': typeof SellerAdsRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/help': typeof SellerHelpRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reports': typeof SellerReportsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/shipping': typeof SellerShippingRoute
  '/seller/stock': typeof SellerStockRoute
  '/seller/subscription': typeof SellerSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/hooks/ad-scheduler': typeof ApiPublicHooksAdSchedulerRoute
  '/api/public/melhor-envio/oauth-callback': typeof ApiPublicMelhorEnvioOauthCallbackRoute
  '/api/public/melhor-envio/webhook': typeof ApiPublicMelhorEnvioWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order/success': typeof OrderSuccessRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/ads': typeof SellerAdsRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/help': typeof SellerHelpRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reports': typeof SellerReportsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/shipping': typeof SellerShippingRoute
  '/seller/stock': typeof SellerStockRoute
  '/seller/subscription': typeof SellerSubscriptionRoute
  '/admin': typeof AdminIndexRoute
  '/seller': typeof SellerIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/hooks/ad-scheduler': typeof ApiPublicHooksAdSchedulerRoute
  '/api/public/melhor-envio/oauth-callback': typeof ApiPublicMelhorEnvioOauthCallbackRoute
  '/api/public/melhor-envio/webhook': typeof ApiPublicMelhorEnvioWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order/success': typeof OrderSuccessRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/ads': typeof SellerAdsRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/help': typeof SellerHelpRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/reports': typeof SellerReportsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/shipping': typeof SellerShippingRoute
  '/seller/stock': typeof SellerStockRoute
  '/seller/subscription': typeof SellerSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/hooks/ad-scheduler': typeof ApiPublicHooksAdSchedulerRoute
  '/api/public/melhor-envio/oauth-callback': typeof ApiPublicMelhorEnvioOauthCallbackRoute
  '/api/public/melhor-envio/webhook': typeof ApiPublicMelhorEnvioWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/messages'
    | '/seller'
    | '/admin/ads'
    | '/admin/banners'
    | '/admin/carousel'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/users'
    | '/admin/vendors'
    | '/category/$slug'
    | '/order/success'
    | '/product/$id'
    | '/seller/ads'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/finance'
    | '/seller/help'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/seller/promotions'
    | '/seller/reports'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/shipping'
    | '/seller/stock'
    | '/seller/subscription'
    | '/admin/'
    | '/seller/'
    | '/api/public/stripe-webhook'
    | '/api/public/hooks/ad-scheduler'
    | '/api/public/melhor-envio/oauth-callback'
    | '/api/public/melhor-envio/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/messages'
    | '/admin/ads'
    | '/admin/banners'
    | '/admin/carousel'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/users'
    | '/admin/vendors'
    | '/category/$slug'
    | '/order/success'
    | '/product/$id'
    | '/seller/ads'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/finance'
    | '/seller/help'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/seller/promotions'
    | '/seller/reports'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/shipping'
    | '/seller/stock'
    | '/seller/subscription'
    | '/admin'
    | '/seller'
    | '/api/public/stripe-webhook'
    | '/api/public/hooks/ad-scheduler'
    | '/api/public/melhor-envio/oauth-callback'
    | '/api/public/melhor-envio/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/messages'
    | '/seller'
    | '/admin/ads'
    | '/admin/banners'
    | '/admin/carousel'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/users'
    | '/admin/vendors'
    | '/category/$slug'
    | '/order/success'
    | '/product/$id'
    | '/seller/ads'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/finance'
    | '/seller/help'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/seller/promotions'
    | '/seller/reports'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/shipping'
    | '/seller/stock'
    | '/seller/subscription'
    | '/admin/'
    | '/seller/'
    | '/api/public/stripe-webhook'
    | '/api/public/hooks/ad-scheduler'
    | '/api/public/melhor-envio/oauth-callback'
    | '/api/public/melhor-envio/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  MessagesRoute: typeof MessagesRoute
  SellerRoute: typeof SellerRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicHooksAdSchedulerRoute: typeof ApiPublicHooksAdSchedulerRoute
  ApiPublicMelhorEnvioOauthCallbackRoute: typeof ApiPublicMelhorEnvioOauthCallbackRoute
  ApiPublicMelhorEnvioWebhookRoute: typeof ApiPublicMelhorEnvioWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/subscription': {
      id: '/seller/subscription'
      path: '/subscription'
      fullPath: '/seller/subscription'
      preLoaderRoute: typeof SellerSubscriptionRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/stock': {
      id: '/seller/stock'
      path: '/stock'
      fullPath: '/seller/stock'
      preLoaderRoute: typeof SellerStockRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/shipping': {
      id: '/seller/shipping'
      path: '/shipping'
      fullPath: '/seller/shipping'
      preLoaderRoute: typeof SellerShippingRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reports': {
      id: '/seller/reports'
      path: '/reports'
      fullPath: '/seller/reports'
      preLoaderRoute: typeof SellerReportsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/promotions': {
      id: '/seller/promotions'
      path: '/promotions'
      fullPath: '/seller/promotions'
      preLoaderRoute: typeof SellerPromotionsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/profile': {
      id: '/seller/profile'
      path: '/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof SellerProfileRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/help': {
      id: '/seller/help'
      path: '/help'
      fullPath: '/seller/help'
      preLoaderRoute: typeof SellerHelpRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/finance': {
      id: '/seller/finance'
      path: '/finance'
      fullPath: '/seller/finance'
      preLoaderRoute: typeof SellerFinanceRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/customers': {
      id: '/seller/customers'
      path: '/customers'
      fullPath: '/seller/customers'
      preLoaderRoute: typeof SellerCustomersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/coupons': {
      id: '/seller/coupons'
      path: '/coupons'
      fullPath: '/seller/coupons'
      preLoaderRoute: typeof SellerCouponsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/ads': {
      id: '/seller/ads'
      path: '/ads'
      fullPath: '/seller/ads'
      preLoaderRoute: typeof SellerAdsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/success': {
      id: '/order/success'
      path: '/order/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carousel': {
      id: '/admin/carousel'
      path: '/carousel'
      fullPath: '/admin/carousel'
      preLoaderRoute: typeof AdminCarouselRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/melhor-envio/webhook': {
      id: '/api/public/melhor-envio/webhook'
      path: '/api/public/melhor-envio/webhook'
      fullPath: '/api/public/melhor-envio/webhook'
      preLoaderRoute: typeof ApiPublicMelhorEnvioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/melhor-envio/oauth-callback': {
      id: '/api/public/melhor-envio/oauth-callback'
      path: '/api/public/melhor-envio/oauth-callback'
      fullPath: '/api/public/melhor-envio/oauth-callback'
      preLoaderRoute: typeof ApiPublicMelhorEnvioOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ad-scheduler': {
      id: '/api/public/hooks/ad-scheduler'
      path: '/api/public/hooks/ad-scheduler'
      fullPath: '/api/public/hooks/ad-scheduler'
      preLoaderRoute: typeof ApiPublicHooksAdSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCarouselRoute: typeof AdminCarouselRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCarouselRoute: AdminCarouselRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerAdsRoute: typeof SellerAdsRoute
  SellerCouponsRoute: typeof SellerCouponsRoute
  SellerCustomersRoute: typeof SellerCustomersRoute
  SellerFinanceRoute: typeof SellerFinanceRoute
  SellerHelpRoute: typeof SellerHelpRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerProfileRoute: typeof SellerProfileRoute
  SellerPromotionsRoute: typeof SellerPromotionsRoute
  SellerReportsRoute: typeof SellerReportsRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerShippingRoute: typeof SellerShippingRoute
  SellerStockRoute: typeof SellerStockRoute
  SellerSubscriptionRoute: typeof SellerSubscriptionRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAdsRoute: SellerAdsRoute,
  SellerCouponsRoute: SellerCouponsRoute,
  SellerCustomersRoute: SellerCustomersRoute,
  SellerFinanceRoute: SellerFinanceRoute,
  SellerHelpRoute: SellerHelpRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerProfileRoute: SellerProfileRoute,
  SellerPromotionsRoute: SellerPromotionsRoute,
  SellerReportsRoute: SellerReportsRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerShippingRoute: SellerShippingRoute,
  SellerStockRoute: SellerStockRoute,
  SellerSubscriptionRoute: SellerSubscriptionRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  MessagesRoute: MessagesRoute,
  SellerRoute: SellerRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicHooksAdSchedulerRoute: ApiPublicHooksAdSchedulerRoute,
  ApiPublicMelhorEnvioOauthCallbackRoute:
    ApiPublicMelhorEnvioOauthCallbackRoute,
  ApiPublicMelhorEnvioWebhookRoute: ApiPublicMelhorEnvioWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
